services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - shareimagemongo:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  redisdb:
    image: redis
    container_name: redisdb
    volumes:
      - shareimageredis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
  elasticsearchdb:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    volumes:
      - shareimageelasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: unless-stopped
volumes:
  shareimagemongo:
  shareimageredis:
  shareimageelasticsearch:
